name: 'Web Build and Deploy'

on:
  # schedule:
  #   - cron:  '10 4,5,10 * * *'
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false 

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
            node-version: '14'

      - name: Install and Build 🔧
        working-directory: web
        run: |
          npm install
          npm run build
          cd build
          cp index.html 404.html
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GIT_CONFIG_NAME: "alphasofthub-bot"
          GIT_CONFIG_EMAIL: "alphasofthub-bot@users.noreply.github.com"
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          FOLDER: web//build
